### ISSUE TITLE
Logs do not handle timezones correctly

### ISSUE THREAD

**Issue by ThrawnCA** [ckan/ckanext-xloader#102]
XLoader logs are generated without specifying a timezone, but then displayed in the web UI as if the timestamps were UTC. This can result in absurd output like `-1 day ago`.

**Comment by Chealer** [comment]
We're also seeing log messages about errors from "4 hours ago", which are about errors that just occurred, as we're in UTC-4, so I guess that confirms the problem.

**Comment by ThrawnCA** [comment]
@Chealer If nothing happens here, we'll probably cut a release of https://github.com/qld-gov-au/ckanext-xloader soon with this patched.

**Comment by ThrawnCA** [comment]
Fixed as part of #166
