### ISSUE TITLE
AttributeError: 'int' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by ash-mcc** [ckan/ckanext-xloader#103]
Running XLoader against a 2.8 CKAN, I see the following error in the log:
`AttributeError: 'int' object has no attribute 'iterates'`

The [installation of a particular version of the Redis Python client](https://github.com/pkumza/LibRadar/issues/64) (and restarting) seems to have made the problem go away. The installation command is:
`pip install redis==2.10.5`

I'm not a Python/CKAN developer and I may well have overlooked something
but this _hack_ might save someone some time. 
(And I'm happy for this issue to be immediately `closed` if appropriate.) 

Cheers, Ash

**Comment by ThrawnCA** [comment]
@ash-mcc Did you also happen to install the Harvest extension? CKAN core 2.8 depends on `redis==2.10.6`, but ckanext-harvest v0.3 depends on `redis>=3.3.0`.
