### ISSUE TITLE
Xloader - Python 3 support

### ISSUE THREAD

**Issue by amercader** [ckan/ckanext-xloader#104]
Placeholder to add it to the Py3 project board, TODO: add actual requirements

**Comment by davidread** [comment]
I've done a lot of the work for this on my own time. I'm looking for a sponsor to pay for the work, before I open source it.

**Comment by davidread** [comment]
I've decided to open up the work I did on this. It's now available on the py3 branch see: https://github.com/ckan/ckanext-xloader/compare/py3

This was a bunch of hacking I did in Feb/March to get Python 3 compatibility and the tests running on both Python 2 and 3. However this work has probably been superseded by @smotornyuk's work which had similar aims: https://github.com/ckan/ckanext-xloader/pull/113 , and has been merged. However maybe there is some value in my branch - maybe someone has the motivation to do some comparison. I'm not working on this now, so I'll just leave this for others to decide on.

**Comment by amercader** [comment]
Done in #113
