### ISSUE TITLE
After remove Datapusher and install xloader still error with DNS lookup

### ISSUE THREAD

**Issue by MichaelHarmsTIB** [ckan/ckanext-xloader#109]
Hi guys,

i got still an error after I remove datapusher from ckan *.ini and install xloader:
DataProxy returned an error (Data transformation failed. error: An error occured while connecting to the server: DNS lookup failed for .....

I follow the steps, except I didn't configure the jobs.
Can someone help me?

**Comment by MichaelHarmsTIB** [comment]
ANother error message is from postgresql db: `datastore_default@datastore_default LOG: could not recieve data from client: Connection reset by peer`

**Comment by duttonw** [comment]
Hi @MichaelHarmsTIB ,

this should be resolved in the lastest pypi release with current ckan versions. 

Please let us know if you continue to have issues.
