### ISSUE TITLE
Request for new maintainer

### ISSUE THREAD

**Issue by davidread** [ckan/ckanext-xloader#112]
I'm not involved with CKAN right now, so I'm welcoming anyone willing to take over the maintaining of this module. There are a few issues and PRs to address, and a simple Travis test breakage to fix up, but generally this should not be an onerous task.

**Comment by davidread** [comment]
I'm happy to announce that @kowh-ai has taken over as maintainer of xloader 👍 👍 👍

**Comment by kowh-ai** [comment]
Thanks @davidread - I'm looking forward to it!
