### ISSUE TITLE
[question] data dictionary

### ISSUE THREAD

**Issue by jeanpommier** [ckan/ckanext-xloader#114]
Hi,
The data dictionary gives a title and definition fields for every column fo the CSV data. What is their use ? I thought it would allow to rename the fields, the same way it allows to change the data types, but apparently not. Have I missed a feature, or is it, for now, not used at all ?
Thanks

**Comment by davidread** [comment]
I'm afraid the readme is not wonderful organized, but the use of the data dictionary can be found: https://github.com/ckan/ckanext-xloader#caveat---column-types - i.e. it's for setting the column types in the Data Store database

Changing a column title compared to the CSV might be something that could be argued, but I fear it is the thin end of a wedge in transforming data before load. There are probably other tools that allow a transform to be described as UI or code, and perform it efficiently. Xloader aims to do the 'L' in ETL well, and my initial thought is against taking on the 'T' stage as well.

**Comment by jeanpommier** [comment]
Hi @davidread ,
Yes, thanks, I had seem this information. I was more wondering about the 2 additional fields (title and definition). Are they used at all ? 
I don't see them used in the database. I'd say that if they are useless, they'd better be removed. If they are of use, I'm curious to know what for

**Comment by davidread** [comment]
xloader makes use of this one field ('type'). Data Dictionary is actually part of DataStore, so it might be better to discuss this aspect with wardi on the main ckan repo.

**Comment by jeanpommier** [comment]
Oh, yes, sorry, you're right. I thought it was an xloader feature
