### ISSUE TITLE
python redis version

### ISSUE THREAD

**Issue by jeanpommier** [ckan/ckanext-xloader#115]
This is related to https://github.com/ckan/ckanext-xloader/issues/103
I have the same issue. It is, indeed, fixed by forcing the python redis version. But I'm also using ckanext-harvest extension, which requires [redis>=3.3.0](https://github.com/ckan/ckanext-harvest/blob/master/pip-requirements.txt) so this is potentially conflicting.
Do anyone have a cleaner solution then ?

**Comment by ThrawnCA** [comment]
XLoader doesn't require any particular Redis version. Whatever ckanext-harvest chooses to install ought to work.

**Comment by duttonw** [comment]
Closing ticket since its been opened since 2020 and no comment from original author from reply back in january 2024.

If you do have an issue please comment and we will reopen this ticket.

Regards,

@duttonw
