### ISSUE TITLE
ODS files fails to upload to DataStore

### ISSUE THREAD

**Issue by quinoescobar** [ckan/ckanext-xloader#143]
### Versions
CKAN 2.9.5
XLoader 0.10.0

 **Describe the bug**

Uploading an ODS file created by code with PyExcel and the extension  ODS3 it fails to get upload to the DataStore.It Fails with ods files created with OpenOffice too.

**Steps to reproduce**

1. Create a simple ODS file.
2. Save it and upload it to a dataset
3. Push the file to the DataStore 
4. Fails and got this message: 
Loading excerpt for this format not supported.
Loading file raised an error: 'utf-8' codec can't decode byte 0xe2 in position 10: invalid continuation byte

With in the XLoader configuration you have to set this propertis to False:
ckanext.xloader.ignore_hash = False
ckanext.xloader.just_load_with_messytables = False

**Expected behavior**
Gets uploaded to the DataStore, create the datadict and creates the configured views.

**Additional details**

If you set ckanext.xloader.just_load_with_messytables = True, the upload to the DataStore it is slower but manage to accomplish the load and all it's OK.

Tracking the problem, I managed to narrow down the cause to this line of code within the load_csv fuction:
https://github.com/ckan/ckanext-xloader/blob/master/ckanext/xloader/loader.py#L51

**Comment by irbian** [comment]
I´m too being affected by this, any workaround?

**Comment by quinoescobar** [comment]
I just updated my testing server to CKAN version 2.9.5 with the last XLoader version(0.10.0) released and the problem persist

**Comment by quinoescobar** [comment]
This issue is solved with the installation of the latest versions of CKAN Core v.2.9.5 and XLoader Extension v.0.11.0 .
