### ISSUE TITLE
Is only first worksheet imported, like datapusher, or complete document?

### ISSUE THREAD

**Issue by jeverling** [ckan/ckanext-xloader#154]
Hi all, datapusher only imports the first worksheet of a XLS file: https://docs.ckan.org/en/2.9/maintaining/datastore.html#datapusher-automatically-add-data-to-the-datastore

How does xloader behave? Is it also only importing the first worksheet, or also additional worksheets?
Thanks!

**Comment by ba-tno** [comment]
99% sure that only the first worksheet is imported as `xloader` uses `messytables` under the hood for XLS files. And messytables only [provide support for a single sheet in the excel workbook](https://messytables.readthedocs.io/en/latest/#excel-support)
