### ISSUE TITLE
Openpyxl cannot be imported

### ISSUE THREAD

**Issue by somikmukh** [ckan/ckanext-xloader#167]
I have installed the openpyxl and can also view it in pip list. However, when trying to use it, getting error:

Exception has occurred: ModuleNotFoundError
No module named 'openpyxl'
  File "<path>.py", line 8, in <module>
    from openpyxl.workbook import Workbook

**Comment by duttonw** [comment]
please try again with latest pypi release. i believe this is now fixed.
