### ISSUE TITLE
No longer installable on Python 2.7

### ISSUE THREAD

**Issue by bellisk** [ckan/ckanext-xloader#169]
I just tried to install this package as part of a deployment, and found that this is no longer possible on Python 2.7.

Version 1.3.0 of pika (which was released on 30.06.2022) requires `setuptools>=61.2`, which is not available for Python 2.7. Actually, pika has not been officially compatible with Py2 since version 1.1.0.

Would it be possible to split `pip-requirements.txt` into a Py2 and a Py3 version?

**Comment by amercader** [comment]
I cleaned up the requirements and removed pika recently as it is not actually needed (https://github.com/ckan/ckanext-xloader/blob/master/requirements.txt). This should be already the case in the latest version 0.11.0, where the [tests pass](https://github.com/ckan/ckanext-xloader/runs/7873279282?check_suite_focus=true) for Py2. Can you check you are using this version?

**Comment by bellisk** [comment]
Thanks, @amercader! I had missed that there was a version that fixed this. All OK now. :)
