### ISSUE TITLE
Store jobs in main ckan database

### ISSUE THREAD

**Issue by davidread** [ckan/ckanext-xloader#17]
rather than a personal ckanext-shift one. The amount of data is relatively small, so not a huge burden. And it saves set-up and something else to manage.

Could usefully delete jobs, so only the latest job for a resource is kept. (since we don't display them anyway)

**Comment by ThrawnCA** [comment]
Note that although XLoader can apparently share the main database, it should *not* share the datastore database. The datastore `set-permissions` script will attempt to treat the XLoader tables as regular datastore tables, which will result in bad things like https://github.com/ckan/ckanext-xloader/issues/83
