### ISSUE TITLE
Check datastore_active on resource update

### ISSUE THREAD

**Issue by ThrawnCA** [ckan/ckanext-xloader#171]
The `datastore_active` flag can sometimes get out of sync with the actual state of the datastore, eg due to race conditions like https://github.com/ckan/ckan/issues/4663

It should be relatively cheap to add an "after update" step to ensure that the flag matches the datastore state.

**Comment by wardi** [comment]
:+1: how about a cli command to update datastore_active for all/some resources as well?

**Comment by wardi** [comment]
That's a good idea. was actually thinking of adding an action to core to reindex a dataset. Maybe things like checking datastore_active, updating tracking counts etc. could be hooked to that action.

**Comment by ThrawnCA** [comment]
A CLI command to bump the state of a dataset could be raised as a separate issue, but the original purpose of this one is complete.
