### ISSUE TITLE
README could mention that XLoader is capable of running on a separate server

### ISSUE THREAD

**Issue by ThrawnCA** [ckan/ckanext-xloader#191]
The README file indicates that one difference between XLoader and DataPusher is that XLoader is designed to run as a worker process on the same machine as CKAN. However, it perhaps should mention that running on a separate server is still entirely possible for those who would prefer that. We run it separately at data.qld.gov.au, it was easy to set up; in some ways easier than DataPusher, since we could just copy the same config file that CKAN uses. It's more scalable that way, especially since we enable type guessing, and it's more isolated from the public network, since it can be on a machine without exposed ports.

**Comment by kowh-ai** [comment]
Thanks @ThrawnCA that would be great!

**Comment by duttonw** [comment]
this can be closed.
