### ISSUE TITLE
Update enqueued job description/comment

### ISSUE THREAD

**Issue by duttonw** [ckan/ckanext-xloader#207]
Ckan job queue can now human commends. This is very useful to allow queue trimming if duplicate heavy jobs are loaded by an author accidentally.

Around this line:
https://github.com/ckan/ckanext-xloader/blob/master/ckanext/xloader/action.py#L157

maybe with title
 job_title = "xloader_job: package_id: {} resource: {}".format(
        package_id, resource_id),

Update to include a nice title like in:
https://github.com/qld-gov-au/ckanext-validation/blob/e9956c2a0003ecff563181a9d8f73770a4a0dc6a/ckanext/validation/logic/action.py#L97
```
def enqueue_validation_job(package_id, resource_id):
    job_title = "run_validation_job: package_id: {} resource: {}".format(
        package_id, resource_id),

    enqueue_args = {
        'fn': run_validation_job,
        'title': job_title,
        'kwargs': {
            'resource': resource_id,
        }
    }

    ttl = 24 * 60 * 60  # 24 hour ttl.
    rq_kwargs = {
        'ttl': ttl, 'failure_ttl': ttl
    }
    enqueue_args['rq_kwargs'] = rq_kwargs

    # Optional variable, if not set, default queue is used
    queue = tk.config.get('ckanext.validation.queue', None)

    if queue:
        enqueue_args['queue'] = queue

    tk.enqueue_job(**enqueue_args)
```

**Comment by ThrawnCA** [comment]
This was already done in #195
