### ISSUE TITLE
Unresponsive resource pages during xloading

### ISSUE THREAD

**Issue by davidread** [ckan/ckanext-xloader#41]
There has been a report that while xloading a large CSV (100Mb+) into Postgres, users find that the resource pages time-out i.e. won't load. Supposedly this occurs to all resource pages, but I've only reproduced it for resources which are large e.g. 4 million rows.

Tests show that the bottleneck is CPU use. The two Postgres' processes involved each get 50% of the CPU, so it's not as if xloader is hogging more than its fair share. Profiling shows the problem is that during previewing a large resource it does SQL command `count(*)` four times, and because there is no indexing this is very expensive for a table with millions of rows.

The site in question has solved the issue by switching to a pair of Postgres replicated instances - the master instance for writes and the slave instance for reads. This required [PR#2562](https://github.com/ckan/ckan/pull/2562) so CKAN 2.8.x or higher, and configuring `ckan.datastore.write_url` and `ckan.datastore.read_url` to the different database instances.

I'm leaving this open for anyone else to make observations of this being an issue or not, with larger datasets (100Mb+ / 1M+ rows).

**Comment by TkTech** [comment]
`COUNT(*)` is always an issue, and not just for postgres. Should probably switch to using the analyzer cache in the `pg_class` table when doing full table counts, and only allow `COUNT` in other scenarios when an index exists on that column.

Also, I've noticed that queries run immediately after a load are extremely slow because the query planner thinks the table is still small and decides to do a full scan. This fixes itself when autovacuum runs and updates the analytics, but it would be better to trigger it ourselves at the end of a load with a setting to disable it.

**Comment by davidread** [comment]
Thanks @TkTech - useful advice. I will hopefully get to work on this before too long.

**Comment by TkTech** [comment]
I'm using xloader in production now, it was far less painful and a marked improvement over datapusher, fantastic work david 👍 Happy to test and review anything!

**Comment by jqnatividad** [comment]
After an xloaded CSV's indices are created, why not add an explicit ANALYZE so we don't need to wait for the next autovacuum?  By default, even for very large tables, [ANALYZE is not an expensive operation as it just samples the table](https://www.postgresql.org/docs/9.6/static/sql-analyze.html).

And if we use the VERBOSE option, Postgres even returns "count" information, e.g.

```SQL
ANALYZE VERBOSE public.summary_view

INFO:  analyzing "public.summary_view"
INFO:  "summary_view": scanned 53406 of 53406 pages, containing 1953580 live rows and 0 dead rows; 300000 rows in sample, 1953580 estimated total rows
ANALYZE

Query returned successfully in 6 secs 395 msec.
```

Note how fast it was even for a large table with 1.9M rows.  And the estimated count actually matched the actual count.

**Comment by davidread** [comment]
Now https://github.com/ckan/ckan/pull/4448 and https://github.com/ckan/ckan/pull/4473 are merged I believe this is no longer an issue. The resource preview is not slow with large datasets any more - the four slow SELECT COUNT(*) commands that caused the issue are all avoided now!

Of course, it needs the 2.9.0 CKAN release to come out and people to upgrade to it, but that won't be long.
