### ISSUE TITLE
xloader ignores datasets uploaded via datastore API

### ISSUE THREAD

**Issue by DerekW24** [ckan/ckanext-xloader#66]
Using CKAN 2.8.2 on Ubuntu, Trying to create a data flow using the ckanapi to define the datasets and resouce metadata, and upload the dataset resources.  Small datasets seem to work fine, 50k-100k rows.  But larger sets like 500k + rows seem to not complete via the API.  They can be uploaded and complete if the web UI is used, though they took a few hours when using datapusher but now just a few minutes with xloader.

I'm using the api/action/datastore_create to upload the dataset resources.  The xloader worker skips over the resources uploaded via the datastore api.  Says "Ignoring resource - url_type=datastore - dump files are managed with the Datastore API"

What API do I use to upload resources so that the xloader will do the work?  or is there a different recommended API/method for larger resources?

Thanks

**Comment by davidread** [comment]
You're using `package_create`, rather than `datastore_create`, right?

**Comment by davidread** [comment]
Hmm that code is from here: https://github.com/ckan/datapusher/pull/81

**Comment by davidread** [comment]
Or if you've got url_type=datastore it suggests you are indeed using `datastore_create`. If that's the case then you're loading the data rows into datastore with that, which is the same thing as xloader does, so maybe that's just a misunderstanding?

xloader looks at the resource.url, downloads it, parses it and then loads the rows into the datastore database. For the last step xloader makes use of `datastore_create` to create the db table, and then directly talks to the db to load the rows.

Perhaps you can just give CKAN the metadata (package_create/update), upload each CSV file with resource_create and then let xloader parse them into datastore? Alternatively, load the data with datastore_create, but that's really slow compared to xloader's method, as you found.

**Comment by DerekW24** [comment]
Good find,  if I use resource_create, xloader will upload the files!  For reference https://github.com/ckan/ckanapi#file-uploads

Now I've used datastore_create to create the resource and its metadata, but resource_create creates a new resource.  So my metadata is not connected to the actual resource.  There are two resources created with the same name.  One with metadata and no data, and one with data but no metadata.  Maybe there is a way to add metadata to an existing resource?

My resources are all csv files, two files per resource.  one csv file with data and the second with the metadata

**Comment by davidread** [comment]
@DerekW24 I think you should be able to change the datastore table name to be what the resource.id (metadata) is. Then you have to set resource extra field 'datastore_enabled'. It might just be easier to start afresh - delete the datastore table and resource (metadata) and upload the file using resource_create.
