### ISSUE TITLE
KeyError: 'resource_id'

### ISSUE THREAD

**Issue by salsa-nathan** [ckan/ckanext-xloader#68]
On current `master` branch, when uploading a resource to datastore I get the following error:

```
  File "/vagrant_data/ckan/default/src/ckanext-xloader/ckanext/xloader/jobs.py", line 378, in set_resource_metadata
    model.Resource.id == update_dict['resource_id']
KeyError: 'resource_id'
```

It appears that the `set_resource_metadata` function in `ckanext/xloader/jobs.py` overwrites the `update_dict` dict:

```
    update_dict = {'datastore_active': update_dict.get('datastore_active', True),
                   'datastore_contains_all_records_of_source_file': update_dict.get('datastore_contains_all_records_of_source_file', True)}
```

...so it no longer contains `resource_id` (see commit: https://github.com/ckan/ckanext-xloader/commit/2a49a51dbab3cff5f4e1afabe0cc73e581abbd86#diff-c548135301733293716337251017abb7)

However it tries to use `update_dict['resource_id']` in the query below:

https://github.com/ckan/ckanext-xloader/blob/master/ckanext/xloader/jobs.py#L378

**Comment by davidread** [comment]
Thanks for the report. Are you able to create a failing test? This would be
a great help fixing it.

**Comment by jeanpommier** [comment]
Hi,
The fix is quite easy:instead of replacing the dict, you just want to update it:
```
update_dict.update({'datastore_active': update_dict.get('datastore_active', True),
                   'datastore_contains_all_records_of_source_file': update_dict.get('datastore_contains_all_records_of_source_file', True)})
```
does the trick

**Comment by davidread** [comment]
@jeanpommier Thanks! A PR with test would be most welcome.

**Comment by jeanpommier** [comment]
Really ? For such a small fix, you need tests with it ? Well sorry but I won't have time right know, I've never written tests on ckan for now and it doesn't seem so easy to me. I can PR without tests for sure. If you need tests, well, it'll have to wait a bit...

**Comment by davidread** [comment]
The extra effort to include tests is much appreciated by the community.

Maybe @stefina can pitch in here, since this issue appears to relate to that work?

**Comment by stefina** [comment]
@davidread Thank you for fixing this! As I was on vacation I missed the notification about this. Sorry!
