### ISSUE TITLE
Unable to see DataStore option on web

### ISSUE THREAD

**Issue by mcsf13m036** [ckan/ckanext-xloader#74]
After configuration of xloader and removal of datapusher from config file, the upload to data store option on ckan resource manage section is disappeared.
![image](https://user-images.githubusercontent.com/10884618/62120896-f769d180-b2db-11e9-8b90-f21e5b9a16f4.png)

This is an issue, because large file upload (e.g. 5GB file using cloudstorage) takes time and xloader fails on first attempt to get the file, so there must be a way to re-trigger it from web when upload done. 

Kindly guide.

**Comment by mcsf13m036** [comment]
pasting error logs:

[Tue Jul 30 10:15:15.749049 2019] [wsgi:error] [pid 9315:tid 140018319984384] [remote 127.0.0.1:5531] File '/usr/lib/ckan/default/lib/python2.7/site-packages/ckanext/xloader/controllers.py', line 49 in resource_data
[Tue Jul 30 10:15:15.749052 2019] [wsgi:error] [pid 9315:tid 140018319984384] [remote 127.0.0.1:5531]   'pkg_dict': p.toolkit.c.pkg_dict,
[Tue Jul 30 10:15:15.749054 2019] [wsgi:error] [pid 9315:tid 140018319984384] [remote 127.0.0.1:5531] File '/usr/lib/ckan/default/src/ckan/ckan/lib/base.py', line 125 in render
[Tue Jul 30 10:15:15.749057 2019] [wsgi:error] [pid 9315:tid 140018319984384] [remote 127.0.0.1:5531]   return cached_template(template_name, renderer)
[Tue Jul 30 10:15:15.749059 2019] [wsgi:error] [pid 9315:tid 140018319984384] [remote 127.0.0.1:5531] File '/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/templating.py', line 249 in cached_template
[Tue Jul 30 10:15:15.749062 2019] [wsgi:error] [pid 9315:tid 140018319984384] [remote 127.0.0.1:5531]   return render_func()
[Tue Jul 30 10:15:15.749064 2019] [wsgi:error] [pid 9315:tid 140018319984384] [remote 127.0.0.1:5531] File '/usr/lib/ckan/default/src/ckan/ckan/lib/base.py', line 142 in render_template
[Tue Jul 30 10:15:15.749066 2019] [wsgi:error] [pid 9315:tid 140018319984384] [remote 127.0.0.1:5531]   template_path, template_type = render_.template_info(template_name)
[Tue Jul 30 10:15:15.749069 2019] [wsgi:error] [pid 9315:tid 140018319984384] [remote 127.0.0.1:5531] File '/usr/lib/ckan/default/src/ckan/ckan/lib/render.py', line 40 in template_info
[Tue Jul 30 10:15:15.749071 2019] [wsgi:error] [pid 9315:tid 140018319984384] [remote 127.0.0.1:5531]   raise TemplateNotFound('Template %s cannot be found' % template_name)
[Tue Jul 30 10:15:15.749074 2019] [wsgi:error] [pid 9315:tid 140018319984384] [remote 127.0.0.1:5531] TemplateNotFound: Template xloader/resource_data.html cannot be found

**Comment by ThrawnCA** [comment]
I can't reproduce this; the upload button is certainly present on our site when we use XLoader. Is it still not working for you?

**Comment by davidread** [comment]
Ah, I think `xloader/resource_data.html cannot be found` is due missing files in the package, meaning you need to `pip install -e git+...` it, or I should add a manifest and do a release.
