### ISSUE TITLE
Error when running populate_full_text_trigger

### ISSUE THREAD

**Issue by ThrawnCA** [ckan/ckanext-xloader#83]
We're trying to set up XLoader on CKAN 2.8.3, but it gets an error whenever it runs. Adding logging statements reveals that the error message is:

  (psycopg2.ProgrammingError) record "new" has no field "_full_text"
  CONTEXT:  SQL statement "SELECT NEW._full_text IS NOT NULL"
  PL/pgSQL function populate_full_text_trigger() line 3 at IF
   [SQL: \\'INSERT INTO jobs (job_id, job_type, status, requested_timestamp, sent_data, result_url, api_key) VALUES (%(job_id)s, %(job_type)s, %(status)s, %(requested_timestamp)s, %(sent_data)s, %(result_url)s, %(api_key)s)\\']

The `populate_full_text_trigger` function definitely exists, with the appropriate content. We've pointed `ckanext.xloader.jobs_db.uri` at the datastore, with the credentials of the database owner.

Any idea why this is happening?

**Comment by ThrawnCA** [comment]
Also tried pointing `ckanext.xloader.jobs_db.uri` at the main database, with the same result. In both cases, XLoader was able to create the jobs, logs, and metadata tables, but did not populate them with any rows.

**Comment by ThrawnCA** [comment]
Ah! Looks like I just didn't clean up properly. I've removed the tables from the datastore database, and kept using the main database, and the problem has gone away.

It appears that the datastore `set-permissions` script tries to apply the full text trigger to all datastore tables, even if they don't have a `_full_text` column.

**Comment by davidread** [comment]
Thanks for recording this. I'm not sure how many more people will encounter this because the README guides people to create a fresh db for ckanext.xloader.jobs_db.uri. So I think having this issue is probably a good enough record of this, if people google the error.

**Comment by Lana-chan** [comment]
> Ah! Looks like I just didn't clean up properly. I've removed the tables from the datastore database, and kept using the main database, and the problem has gone away.

@ThrawnCA could you elaborate please on these steps? We're trying to migrate an old 2.7 database and datastore to 2.10 replacing datapusher with xloader and I'm running into the same populate_full_text_trigger issue. We've followed the readme instructions to use the main CKAN database, not the datastore one. Also the following command from the readme:

`ckan -c /etc/ckan/default/ckan.ini migrate_types`

returns `Error: No such command 'migrate_types'.`

**Comment by ThrawnCA** [comment]
@Lana-chan So you get an error when running the script generated by `ckan datastore set-permissions`?

Unfortunately I don't think you'll have success in migrating directly from 2.7 to 2.10. The `migrate_types` command was part of the old Paster style of execution, which was only used up to CKAN 2.8, and the functionality was not added to the newer Click based CLI. However, if you set the `ckanext.xloader.use_type_guessing` flag, then your system should be able to repopulate the types going forward.

**Comment by Lana-chan** [comment]
> @Lana-chan So you get an error when running the script generated by `ckan datastore set-permissions`?

I do not. Wow, that's all I needed to do, XLoader seems to be working fine now, uploaded to datastore without issues. I guess I assumed the permissions didn't need to be updated since we performed a full pg_restore with the same DB users, and the docs made it seem like the permissions needed to be set only on a new database, so I was afraid of affecting the existing data.

Looks like all our old datasets are also still intact, however due to the deprecation of recline views unless I manually re-enable them, they all need to have a Datatable view manually added... Is there a script that updates that? (Unrelated to this issue, I know, but if there's anywhere you could point me or where I can ask this better, I'd appreciate it)
