### ISSUE TITLE
Import existing column types into data dictionary?

### ISSUE THREAD

**Issue by ThrawnCA** [ckan/ckanext-xloader#84]
We have a CKAN system that has been using the DataPusher, and we want to migrate to XLoader to improve performance and reduce administration overheads. However, we have thousands of resources parsed by messytables, and we want to preserve the type information (to format the data better for client applications), which XLoader doesn't by default.

To avoid updating each resource manually, we're looking at writing a paster command to inspect the existing columns and add Data Dictionary overrides for all of the non-text fields for when we move to XLoader.

Are there any obvious pitfalls with this approach?

**Comment by davidread** [comment]
That sounds great! i.e. writing the data dictionary for resources that have already been datapushed

Do add something to the README too to suggest people run this when migrating from datapusher.

**Comment by ThrawnCA** [comment]
Just a note, this has now been run on www.data.qld.gov.au, with 11891 resources, and took about 4 hours the first time. Re-running it, however, took just a few minutes.

**Comment by davidread** [comment]
Awesome!
