### ISSUE TITLE
Bulk reload to the datastore

### ISSUE THREAD

**Issue by clauded** [ckan/ckanext-xloader#88]
I'm migrating a CKAN 2.4 instance to 2.8.3 and planning to switch from datapusher to xloader. Our 2.4 datastore behaves strangely: many datasets are in the datastore but preview still uses dataproxy to visualize those datasets.
Instead of restoring this buggy datastore, is there a way to bulk reload it from our local files?

**Comment by clauded** [comment]
Replying to myself here: it's as simple as `paster --plugin=ckanext-xloader xloader submit all`. Other options can be found here: https://github.com/ckan/ckanext-xloader/blob/master/ckanext/xloader/cli.py.

Maybe a documentation update would be useful?

**Comment by davidread** [comment]
Yeah the README just has:
```
For a full list of XLoader commands:

paster --plugin=ckanext-xloader xloader --help
```
But happy to accept PRs that improve it!

Closing as the original issue is covered by existing functionality.
