### ISSUE TITLE
Except wrong Exception in xloader_data_into_datastore_

### ISSUE THREAD

**Issue by pdelboca** [ckan/ckanext-xloader#93]
When running `xloader_data_into_datastore_` there is a try/except to wait 5 seconds if CKAN gets slow to create the resource:
https://github.com/ckan/ckanext-xloader/blob/5313a12ce19014ab25d7c361dc1f5eb5f7e83cd5/ckanext/xloader/jobs.py#L137-L142

The problem is that `get_resource_and_dataset(resource_id)` does not raise a JobError, only `NotFound` (because inside it calls `resource_show` and `package_show`) so this exception is never caught making xloader raise a NotFound exception.

With some guidelines I can do a PR, not sure if there is something else behind that I am missing.

**Comment by davidread** [comment]
Thanks for spotting this - yes I believe you're right that we'd get a 404 in this case. I'll do a PR.

**Comment by stefina** [comment]
@davidread are there any plans on a new release of xloader soon that contains this fix? As I see it https://github.com/ckan/ckanext-xloader/releases/tag/0.5.0 was released a day before this was reported and we would also benefit from this fix.

**Comment by davidread** [comment]
No problem, I've done a release - 0.6.0 which includes this PR.

**Comment by stefina** [comment]
Thank you so much :) Unfortunately I can not see it neither under releases nor in the tags. Am I missing something or can you provide a link?

**Comment by davidread** [comment]
@stefina Apologies, I made an error in the release. Release 0.6.1 is now available. Thanks for your patience.

**Comment by stefina** [comment]
No worries, I see it now, thank you for double-checking :)
